import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Footer, Header, Main, Page } from '../components/Common'
import { BrandH } from '../components/Heading'

const Home: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <BrandH>
          <Link href="/"> Playground </Link>
        </BrandH>
      </Header>

      <Main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </Main>
      <Footer>

      </Footer>
    </Page>
  )
}

export default Home
