import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Footer, Header, Main, Page } from '../components/Common'
import { BrandH, H1, P } from '../components/Text'
import { Section1, Section2 } from '../components/Section'
import { Theme } from '../components/Theme/Index'
import { DataBox } from '../components/DataBox'

const Home: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <BrandH>
          <Link href="/"> Playground </Link>
        </BrandH>
        <Theme/>
      </Header>

      <Main>
        <Section1>
          <H1>Playground Place</H1>
          <P>A place to test and improve my skills</P>
        </Section1>
        <Section2>
          <DataBox/>
        </Section2>
      </Main>
      <Footer>

      </Footer>
    </Page>
  )
}

export default Home
